<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AddonSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks temporarily
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('addon_settings')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $data = [
            ['id' => '070c6bbd-d777-11ed-96f4-0c7a158e4469', 'key_name' => 'twilio', 'live_values' => '{"gateway":"twilio","mode":"live","status":"0","sid":"data","messaging_service_sid":"data","token":"data","from":"data","otp_template":"data"}', 'test_values' => '{"gateway":"twilio","mode":"live","status":"0","sid":"data","messaging_service_sid":"data","token":"data","from":"data","otp_template":"data"}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => '2023-08-12 07:01:29', 'additional_data' => null],
            // ['id' => '070c766c-d777-11ed-96f4-0c7a158e4469', 'key_name' => '2factor', 'live_values' => '{"gateway":"2factor","mode":"live","status":"0","api_key":"data"}', 'test_values' => '{"gateway":"2factor","mode":"live","status":"0","api_key":"data"}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => '2023-08-12 07:01:36', 'additional_data' => null],
            ['id' => '1821029f-d776-11ed-96f4-0c7a158e4469', 'key_name' => 'msg91', 'live_values' => '{"gateway":"msg91","mode":"live","status":"0","template_id":"data","auth_key":"data"}', 'test_values' => '{"gateway":"msg91","mode":"live","status":"0","template_id":"data","auth_key":"data"}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => '2023-08-12 07:01:48', 'additional_data' => null],
            ['id' => '18210f2b-d776-11ed-96f4-0c7a158e4469', 'key_name' => 'nexmo', 'live_values' => '{"gateway":"nexmo","mode":"live","status":"0","api_key":"","api_secret":"","token":"","from":"","otp_template":""}', 'test_values' => '{"gateway":"nexmo","mode":"live","status":"0","api_key":"","api_secret":"","token":"","from":"","otp_template":""}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => '2023-04-10 02:14:44', 'additional_data' => null],
            ['id' => '68579846-d8e8-11ed-8249-0c7a158e4469', 'key_name' => 'alphanet_sms', 'live_values' => '{"gateway":"alphanet_sms","mode":"live","status":0,"api_key":"","otp_template":""}', 'test_values' => '{"gateway":"alphanet_sms","mode":"live","status":0,"api_key":"","otp_template":""}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
            ['id' => '6857a2e8-d8e8-11ed-8249-0c7a158e4469', 'key_name' => 'sms_to', 'live_values' => '{"gateway":"sms_to","mode":"live","status":0,"api_key":"","sender_id":"","otp_template":""}', 'test_values' => '{"gateway":"sms_to","mode":"live","status":0,"api_key":"","sender_id":"","otp_template":""}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
            ['id' => 'b6c333f6-d8e9-11ed-8249-0c7a158e4469', 'key_name' => 'akandit_sms', 'live_values' => '{"gateway":"akandit_sms","mode":"live","status":0,"username":"","password":"","otp_template":""}', 'test_values' => '{"gateway":"akandit_sms","mode":"live","status":0,"username":"","password":"","otp_template":""}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
            ['id' => 'b6c33c87-d8e9-11ed-8249-0c7a158e4469', 'key_name' => 'global_sms', 'live_values' => '{"gateway":"global_sms","mode":"live","status":0,"user_name":"","password":"","from":"","otp_template":""}', 'test_values' => '{"gateway":"global_sms","mode":"live","status":0,"user_name":"","password":"","from":"","otp_template":""}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
            ['id' => 'cb0081ce-d775-11ed-96f4-0c7a158e4469', 'key_name' => 'releans', 'live_values' => '{"gateway":"releans","mode":"live","status":0,"api_key":"","from":"","otp_template":""}', 'test_values' => '{"gateway":"releans","mode":"live","status":0,"api_key":"","from":"","otp_template":""}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => '2023-04-10 02:14:44', 'additional_data' => null],
            ['id' => 'e0450278-d8eb-11ed-8249-0c7a158e4469', 'key_name' => 'signal_wire', 'live_values' => '{"gateway":"signal_wire","mode":"live","status":0,"project_id":"","token":"","space_url":"","from":"","otp_template":""}', 'test_values' => '{"gateway":"signal_wire","mode":"live","status":0,"project_id":"","token":"","space_url":"","from":"","otp_template":""}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
            ['id' => 'e0450b40-d8eb-11ed-8249-0c7a158e4469', 'key_name' => 'paradox', 'live_values' => '{"gateway":"paradox","mode":"live","status":"0","api_key":"","sender_id":""}', 'test_values' => '{"gateway":"paradox","mode":"live","status":"0","api_key":"","sender_id":""}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => '2023-09-10 01:14:01', 'additional_data' => null],
            ['id' => 'eed88336-d8ec-11ed-8249-0c7a158e4469', 'key_name' => 'hubtel', 'live_values' => '{"gateway":"hubtel","mode":"live","status":0,"sender_id":"","client_id":"","client_secret":"","otp_template":""}', 'test_values' => '{"gateway":"hubtel","mode":"live","status":0,"sender_id":"","client_id":"","client_secret":"","otp_template":""}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
            ['id' => 'f149c546-d8ea-11ed-8249-0c7a158e4469', 'key_name' => 'viatech', 'live_values' => '{"gateway":"viatech","mode":"live","status":0,"api_url":"","api_key":"","sender_id":"","otp_template":""}', 'test_values' => '{"gateway":"viatech","mode":"live","status":0,"api_url":"","api_key":"","sender_id":"","otp_template":""}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
            ['id' => 'f149cd9c-d8ea-11ed-8249-0c7a158e4469', 'key_name' => '019_sms', 'live_values' => '{"gateway":"019_sms","mode":"live","status":0,"password":"","username":"","username_for_token":"","sender":"","otp_template":""}', 'test_values' => '{"gateway":"019_sms","mode":"live","status":0,"password":"","username":"","username_for_token":"","sender":"","otp_template":""}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
            ['id' => 'f149cd9d-d8ea-11ed-8249-0c7a158e4469', 'key_name' => 'bulksmsbd', 'live_values' => '{"gateway":"bulksmsbd","mode":"live","status":"0","api_key":"X8YYwQMHRJFFB6uosHmf","senderid":"8809617619693","otp_template":"Your OTP code is: {code}"}', 'test_values' => '{"gateway":"bulksmsbd","mode":"live","status":"0","api_key":"","senderid":"","otp_template":"Your OTP code is: {code}"}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
            ['id' => 'f149cd9e-d8ea-11ed-8249-0c7a158e4469', 'key_name' => 'mram_sms', 'live_values' => '{"gateway":"mram_sms","mode":"live","status":"0","api_key":"C3001649692a96112173b8.19807200","userId":"C3001649","password":"SODNySA4Vl","senderid":"TRADELINK","otp_template":"Your OTP code is: {code}"}', 'test_values' => '{"gateway":"mram_sms","mode":"live","status":"0","api_key":"C3001649692a96112173b8.19807200","userId":"C3001649","password":"SODNySA4Vl","senderid":"TRADELINK","otp_template":"Your OTP code is: {code}"}', 'settings_type' => 'sms_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
            
            // Email Configuration
            ['id' => 'e149cd9e-d8ea-11ed-8249-0c7a158e4469', 'key_name' => 'smtp', 'live_values' => '{"gateway":"smtp","mode":"live","status":"0","host":"","port":587,"username":"","password":"","encryption":"tls","from_address":"","from_name":""}', 'test_values' => '{"gateway":"smtp","mode":"live","status":"0","host":"","port":587,"username":"","password":"","encryption":"tls","from_address":"","from_name":""}', 'settings_type' => 'email_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
            ['id' => 'e149cd9f-d8ea-11ed-8249-0c7a158e4469', 'key_name' => 'mailgun', 'live_values' => '{"gateway":"mailgun","mode":"live","status":"0","domain":"","secret":""}', 'test_values' => '{"gateway":"mailgun","mode":"live","status":"0","domain":"","secret":""}', 'settings_type' => 'email_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
            ['id' => 'e149cda0-d8ea-11ed-8249-0c7a158e4469', 'key_name' => 'ses', 'live_values' => '{"gateway":"ses","mode":"live","status":"0","key":"","secret":"","region":"us-east-1"}', 'test_values' => '{"gateway":"ses","mode":"live","status":"0","key":"","secret":"","region":"us-east-1"}', 'settings_type' => 'email_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
            ['id' => 'e149cda1-d8ea-11ed-8249-0c7a158e4469', 'key_name' => 'postmark', 'live_values' => '{"gateway":"postmark","mode":"live","status":"0","token":""}', 'test_values' => '{"gateway":"postmark","mode":"live","status":"0","token":""}', 'settings_type' => 'email_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
            ['id' => 'e149cda2-d8ea-11ed-8249-0c7a158e4469', 'key_name' => 'sendgrid', 'live_values' => '{"gateway":"sendgrid","mode":"live","status":"0","api_key":"","from_address":"","from_name":""}', 'test_values' => '{"gateway":"sendgrid","mode":"live","status":"0","api_key":"","from_address":"","from_name":""}', 'settings_type' => 'email_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
            ['id' => 'e149cda3-d8ea-11ed-8249-0c7a158e4469', 'key_name' => 'resend', 'live_values' => '{"gateway":"resend","mode":"live","status":"0","api_key":"","from_address":"","from_name":""}', 'test_values' => '{"gateway":"resend","mode":"live","status":"0","api_key":"","from_address":"","from_name":""}', 'settings_type' => 'email_config', 'mode' => 'live', 'is_active' => 0, 'created_at' => null, 'updated_at' => null, 'additional_data' => null],
        ];

        // Add payment configs (keeping only SMS configs for now, can add payment configs later if needed)
        foreach ($data as $item) {
            DB::table('addon_settings')->insert($item);
        }
    }
}
